language: java

jdk:
    - oraclejdk7

services:
    - mysql

before_install: 
    - cd MainHk
    - mysql -uroot -e "grant all on belajar.* to belajar@localhost identified by 'java'"
    - mysql -uroot -e "drop database if exists hk"
    - mysql -uroot -e "create database hk"
script: mvn clean install -DskipTests

